# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: suggestions.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11suggestions.proto\x12\x0bsuggestions\"F\n\x11SuggestionRequest\x12\x0f\n\x07orderId\x18\x01 \x01(\t\x12 \n\x05items\x18\x02 \x03(\x0b\x32\x11.suggestions.Item\"6\n\x12SuggestionResponse\x12 \n\x05\x62ooks\x18\x01 \x03(\x0b\x32\x11.suggestions.Book\"&\n\x04Item\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"5\n\x04\x42ook\x12\x0e\n\x06\x62ookId\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t2h\n\x11SuggestionService\x12S\n\x0egetSuggestions\x12\x1e.suggestions.SuggestionRequest\x1a\x1f.suggestions.SuggestionResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'suggestions_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SUGGESTIONREQUEST']._serialized_start=34
  _globals['_SUGGESTIONREQUEST']._serialized_end=104
  _globals['_SUGGESTIONRESPONSE']._serialized_start=106
  _globals['_SUGGESTIONRESPONSE']._serialized_end=160
  _globals['_ITEM']._serialized_start=162
  _globals['_ITEM']._serialized_end=200
  _globals['_BOOK']._serialized_start=202
  _globals['_BOOK']._serialized_end=255
  _globals['_SUGGESTIONSERVICE']._serialized_start=257
  _globals['_SUGGESTIONSERVICE']._serialized_end=361
# @@protoc_insertion_point(module_scope)
