# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from fraud_detection import fraud_detection_pb2 as fraud__detection_dot_fraud__detection__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from utils import utils_pb2 as utils_dot_utils__pb2


class FraudDetectionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitOrder = channel.unary_unary(
                '/fraud_detection.FraudDetectionService/InitOrder',
                request_serializer=fraud__detection_dot_fraud__detection__pb2.InitializationRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.CheckUserData = channel.unary_unary(
                '/fraud_detection.FraudDetectionService/CheckUserData',
                request_serializer=utils_dot_utils__pb2.ContinuationRequest.SerializeToString,
                response_deserializer=fraud__detection_dot_fraud__detection__pb2.DetectionResponse.FromString,
                )
        self.CheckCreditCard = channel.unary_unary(
                '/fraud_detection.FraudDetectionService/CheckCreditCard',
                request_serializer=utils_dot_utils__pb2.ContinuationRequest.SerializeToString,
                response_deserializer=fraud__detection_dot_fraud__detection__pb2.DetectionResponse.FromString,
                )
        self.ClearOrder = channel.unary_unary(
                '/fraud_detection.FraudDetectionService/ClearOrder',
                request_serializer=utils_dot_utils__pb2.ContinuationRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class FraudDetectionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InitOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckUserData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckCreditCard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FraudDetectionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.InitOrder,
                    request_deserializer=fraud__detection_dot_fraud__detection__pb2.InitializationRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'CheckUserData': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckUserData,
                    request_deserializer=utils_dot_utils__pb2.ContinuationRequest.FromString,
                    response_serializer=fraud__detection_dot_fraud__detection__pb2.DetectionResponse.SerializeToString,
            ),
            'CheckCreditCard': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckCreditCard,
                    request_deserializer=utils_dot_utils__pb2.ContinuationRequest.FromString,
                    response_serializer=fraud__detection_dot_fraud__detection__pb2.DetectionResponse.SerializeToString,
            ),
            'ClearOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearOrder,
                    request_deserializer=utils_dot_utils__pb2.ContinuationRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fraud_detection.FraudDetectionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FraudDetectionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InitOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fraud_detection.FraudDetectionService/InitOrder',
            fraud__detection_dot_fraud__detection__pb2.InitializationRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckUserData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fraud_detection.FraudDetectionService/CheckUserData',
            utils_dot_utils__pb2.ContinuationRequest.SerializeToString,
            fraud__detection_dot_fraud__detection__pb2.DetectionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckCreditCard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fraud_detection.FraudDetectionService/CheckCreditCard',
            utils_dot_utils__pb2.ContinuationRequest.SerializeToString,
            fraud__detection_dot_fraud__detection__pb2.DetectionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ClearOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fraud_detection.FraudDetectionService/ClearOrder',
            utils_dot_utils__pb2.ContinuationRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
