# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fraud_detection.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x66raud_detection.proto\x12\x0f\x66raud_detection\"\xbd\x01\n\x15\x46raudDetectionRequest\x12\x0f\n\x07orderId\x18\x01 \x01(\x05\x12#\n\x04user\x18\x02 \x01(\x0b\x32\x15.fraud_detection.User\x12$\n\x05items\x18\x03 \x03(\x0b\x32\x15.fraud_detection.Item\x12\x30\n\x0e\x62illingAddress\x18\x04 \x01(\x0b\x32\x18.fraud_detection.Address\x12\x16\n\x0eshippingMethod\x18\x05 \x01(\t\".\n\x16\x46raudDetectionResponse\x12\x14\n\x0cisFraudulent\x18\x01 \x01(\x08\"%\n\x04User\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontact\x18\x02 \x01(\t\"&\n\x04Item\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"T\n\x07\x41\x64\x64ress\x12\x0e\n\x06street\x18\x01 \x01(\t\x12\x0c\n\x04\x63ity\x18\x02 \x01(\t\x12\r\n\x05state\x18\x03 \x01(\t\x12\x0b\n\x03zip\x18\x04 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x05 \x01(\t2y\n\x15\x46raudDetectionService\x12`\n\x0b\x44\x65tectFraud\x12&.fraud_detection.FraudDetectionRequest\x1a\'.fraud_detection.FraudDetectionResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fraud_detection_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FRAUDDETECTIONREQUEST']._serialized_start=43
  _globals['_FRAUDDETECTIONREQUEST']._serialized_end=232
  _globals['_FRAUDDETECTIONRESPONSE']._serialized_start=234
  _globals['_FRAUDDETECTIONRESPONSE']._serialized_end=280
  _globals['_USER']._serialized_start=282
  _globals['_USER']._serialized_end=319
  _globals['_ITEM']._serialized_start=321
  _globals['_ITEM']._serialized_end=359
  _globals['_ADDRESS']._serialized_start=361
  _globals['_ADDRESS']._serialized_end=445
  _globals['_FRAUDDETECTIONSERVICE']._serialized_start=447
  _globals['_FRAUDDETECTIONSERVICE']._serialized_end=568
# @@protoc_insertion_point(module_scope)
