# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from books_database import books_database_pb2 as books__database_dot_books__database__pb2


class BooksDatabaseStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Read = channel.unary_unary(
                '/books_database.BooksDatabase/Read',
                request_serializer=books__database_dot_books__database__pb2.ReadRequest.SerializeToString,
                response_deserializer=books__database_dot_books__database__pb2.ReadResponse.FromString,
                )
        self.PrepareWrite = channel.unary_unary(
                '/books_database.BooksDatabase/PrepareWrite',
                request_serializer=books__database_dot_books__database__pb2.WriteRequest.SerializeToString,
                response_deserializer=books__database_dot_books__database__pb2.PrepareResponse.FromString,
                )
        self.PrepareIncrementStock = channel.unary_unary(
                '/books_database.BooksDatabase/PrepareIncrementStock',
                request_serializer=books__database_dot_books__database__pb2.WriteRequest.SerializeToString,
                response_deserializer=books__database_dot_books__database__pb2.PrepareResponse.FromString,
                )
        self.PrepareDecrementStock = channel.unary_unary(
                '/books_database.BooksDatabase/PrepareDecrementStock',
                request_serializer=books__database_dot_books__database__pb2.WriteRequest.SerializeToString,
                response_deserializer=books__database_dot_books__database__pb2.PrepareResponse.FromString,
                )
        self.CommitWrite = channel.unary_unary(
                '/books_database.BooksDatabase/CommitWrite',
                request_serializer=books__database_dot_books__database__pb2.TransactionRequest.SerializeToString,
                response_deserializer=books__database_dot_books__database__pb2.CommitResponse.FromString,
                )
        self.AbortWrite = channel.unary_unary(
                '/books_database.BooksDatabase/AbortWrite',
                request_serializer=books__database_dot_books__database__pb2.TransactionRequest.SerializeToString,
                response_deserializer=books__database_dot_books__database__pb2.AbortResponse.FromString,
                )


class BooksDatabaseServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Read(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PrepareWrite(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PrepareIncrementStock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PrepareDecrementStock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitWrite(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AbortWrite(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BooksDatabaseServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Read': grpc.unary_unary_rpc_method_handler(
                    servicer.Read,
                    request_deserializer=books__database_dot_books__database__pb2.ReadRequest.FromString,
                    response_serializer=books__database_dot_books__database__pb2.ReadResponse.SerializeToString,
            ),
            'PrepareWrite': grpc.unary_unary_rpc_method_handler(
                    servicer.PrepareWrite,
                    request_deserializer=books__database_dot_books__database__pb2.WriteRequest.FromString,
                    response_serializer=books__database_dot_books__database__pb2.PrepareResponse.SerializeToString,
            ),
            'PrepareIncrementStock': grpc.unary_unary_rpc_method_handler(
                    servicer.PrepareIncrementStock,
                    request_deserializer=books__database_dot_books__database__pb2.WriteRequest.FromString,
                    response_serializer=books__database_dot_books__database__pb2.PrepareResponse.SerializeToString,
            ),
            'PrepareDecrementStock': grpc.unary_unary_rpc_method_handler(
                    servicer.PrepareDecrementStock,
                    request_deserializer=books__database_dot_books__database__pb2.WriteRequest.FromString,
                    response_serializer=books__database_dot_books__database__pb2.PrepareResponse.SerializeToString,
            ),
            'CommitWrite': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitWrite,
                    request_deserializer=books__database_dot_books__database__pb2.TransactionRequest.FromString,
                    response_serializer=books__database_dot_books__database__pb2.CommitResponse.SerializeToString,
            ),
            'AbortWrite': grpc.unary_unary_rpc_method_handler(
                    servicer.AbortWrite,
                    request_deserializer=books__database_dot_books__database__pb2.TransactionRequest.FromString,
                    response_serializer=books__database_dot_books__database__pb2.AbortResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'books_database.BooksDatabase', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BooksDatabase(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Read(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/books_database.BooksDatabase/Read',
            books__database_dot_books__database__pb2.ReadRequest.SerializeToString,
            books__database_dot_books__database__pb2.ReadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PrepareWrite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/books_database.BooksDatabase/PrepareWrite',
            books__database_dot_books__database__pb2.WriteRequest.SerializeToString,
            books__database_dot_books__database__pb2.PrepareResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PrepareIncrementStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/books_database.BooksDatabase/PrepareIncrementStock',
            books__database_dot_books__database__pb2.WriteRequest.SerializeToString,
            books__database_dot_books__database__pb2.PrepareResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PrepareDecrementStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/books_database.BooksDatabase/PrepareDecrementStock',
            books__database_dot_books__database__pb2.WriteRequest.SerializeToString,
            books__database_dot_books__database__pb2.PrepareResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CommitWrite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/books_database.BooksDatabase/CommitWrite',
            books__database_dot_books__database__pb2.TransactionRequest.SerializeToString,
            books__database_dot_books__database__pb2.CommitResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AbortWrite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/books_database.BooksDatabase/AbortWrite',
            books__database_dot_books__database__pb2.TransactionRequest.SerializeToString,
            books__database_dot_books__database__pb2.AbortResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
