# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order_queue/order_queue.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from utils import utils_pb2 as utils_dot_utils__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dorder_queue/order_queue.proto\x12\x0border_queue\x1a\x1bgoogle/protobuf/empty.proto\x1a\x11utils/utils.proto\"Y\n\x0e\x45nqueueRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x19\n\x04user\x18\x02 \x01(\x0b\x32\x0b.utils.User\x12\x1a\n\x05items\x18\x03 \x03(\x0b\x32\x0b.utils.Item\"\"\n\x0f\x45nqueueResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"?\n\x0f\x44\x65queueResponse\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x1a\n\x05items\x18\x02 \x03(\x0b\x32\x0b.utils.Item2\x9e\x01\n\x11OrderQueueService\x12\x46\n\x07\x45nqueue\x12\x1b.order_queue.EnqueueRequest\x1a\x1c.order_queue.EnqueueResponse\"\x00\x12\x41\n\x07\x44\x65queue\x12\x16.google.protobuf.Empty\x1a\x1c.order_queue.DequeueResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_queue.order_queue_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ENQUEUEREQUEST']._serialized_start=94
  _globals['_ENQUEUEREQUEST']._serialized_end=183
  _globals['_ENQUEUERESPONSE']._serialized_start=185
  _globals['_ENQUEUERESPONSE']._serialized_end=219
  _globals['_DEQUEUERESPONSE']._serialized_start=221
  _globals['_DEQUEUERESPONSE']._serialized_end=284
  _globals['_ORDERQUEUESERVICE']._serialized_start=287
  _globals['_ORDERQUEUESERVICE']._serialized_end=445
# @@protoc_insertion_point(module_scope)
