# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order_executor/order_executor.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#order_executor/order_executor.proto\x12\x0eorder_executor\x1a\x1bgoogle/protobuf/empty.proto\"\x1e\n\x10\x45xecutorResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x32\xe3\x01\n\x14OrderExecutorService\x12\x42\n\x04Ping\x12\x16.google.protobuf.Empty\x1a .order_executor.ExecutorResponse\"\x00\x12\x46\n\x08\x45lection\x12\x16.google.protobuf.Empty\x1a .order_executor.ExecutorResponse\"\x00\x12?\n\x0b\x43oordinator\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_executor.order_executor_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EXECUTORRESPONSE']._serialized_start=84
  _globals['_EXECUTORRESPONSE']._serialized_end=114
  _globals['_ORDEREXECUTORSERVICE']._serialized_start=117
  _globals['_ORDEREXECUTORSERVICE']._serialized_end=344
# @@protoc_insertion_point(module_scope)
