# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payment/payment.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15payment/payment.proto\x12\x07payment\x1a\x1bgoogle/protobuf/empty.proto\"2\n\x0ePaymentRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x01\" \n\x0fPrepareResponse\x12\r\n\x05ready\x18\x01 \x01(\x08\"!\n\x0e\x43ommitResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\" \n\rAbortResponse\x12\x0f\n\x07\x61\x62orted\x18\x01 \x01(\x08\x32\xca\x01\n\x0ePaymentService\x12>\n\x07Prepare\x12\x17.payment.PaymentRequest\x1a\x18.payment.PrepareResponse\"\x00\x12<\n\x06\x43ommit\x12\x17.payment.PaymentRequest\x1a\x17.payment.CommitResponse\"\x00\x12:\n\x05\x41\x62ort\x12\x17.payment.PaymentRequest\x1a\x16.payment.AbortResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payment.payment_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PAYMENTREQUEST']._serialized_start=63
  _globals['_PAYMENTREQUEST']._serialized_end=113
  _globals['_PREPARERESPONSE']._serialized_start=115
  _globals['_PREPARERESPONSE']._serialized_end=147
  _globals['_COMMITRESPONSE']._serialized_start=149
  _globals['_COMMITRESPONSE']._serialized_end=182
  _globals['_ABORTRESPONSE']._serialized_start=184
  _globals['_ABORTRESPONSE']._serialized_end=216
  _globals['_PAYMENTSERVICE']._serialized_start=219
  _globals['_PAYMENTSERVICE']._serialized_end=421
# @@protoc_insertion_point(module_scope)
